import { StyleSheet } from "react-native";
import { C } from "@/constants/Colors";

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.dark },
  center: {
    flex: 1,
    backgroundColor: C.dark,
    alignItems: "center",
    justifyContent: "center",
  },
  errorText: { color: C.white40, fontSize: 16, marginBottom: 20 },
  backBtn: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: C.dark3,
    borderWidth: 1,
    borderColor: C.gold33,
  },
  backBtnText: { color: C.gold, fontWeight: "700" },

  hero: { padding: 24, paddingBottom: 28, overflow: "hidden" },
  backRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 20,
  },
  backArrow: { color: C.gold, fontSize: 20 },
  backLabel: { color: C.white40, fontSize: 14 },

  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
    gap: 12,
  },
  heroTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 4,
  },
  heroSub: { color: C.white40, fontSize: 12 },
  liveBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(228,75,75,0.15)",
    borderWidth: 1,
    borderColor: "rgba(228,75,75,0.4)",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  livePulse: { width: 7, height: 7, borderRadius: 3.5, backgroundColor: C.red },
  liveBadgeText: {
    color: C.red,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
  },

  vsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sideBox: { flex: 1 },
  colorDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginBottom: 6,
    borderWidth: 1,
  },
  whiteDot: { backgroundColor: "#fff", borderColor: C.white35 },
  blackDot: { backgroundColor: "#1a1a2a", borderColor: C.white35 },
  playerName: { color: "#fff", fontSize: 14, fontWeight: "700" },
  playerTitle: { color: C.gold, fontSize: 11, fontWeight: "700" },
  playerRating: { color: C.white40, fontSize: 12 },
  vsText: {
    color: C.white35,
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 2,
  },

  section: { paddingHorizontal: 20, marginTop: 24 },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  sectionTitle: { color: "#fff", fontSize: 15, fontWeight: "700" },
  movesCount: { color: C.white35, fontWeight: "400", fontSize: 13 },
  newMovePill: {
    backgroundColor: "rgba(100,220,100,0.15)",
    borderWidth: 1,
    borderColor: "rgba(100,220,100,0.45)",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  newMovePillText: {
    color: "#64dc64",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  noFen: { alignItems: "center", paddingVertical: 24 },
  noFenText: { color: C.white35, fontSize: 13 },

  infoCard: {
    backgroundColor: C.dark3,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.white6,
    overflow: "hidden",
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 13,
    gap: 20,
  },
  infoRowBorder: { borderTopWidth: 1, borderTopColor: C.white4 },
  infoLabel: { color: C.white40, fontSize: 13 },
  infoVal: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "600",
    flex: 1,
    textAlign: "right",
  },

  movesCard: {
    backgroundColor: C.dark3,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.white6,
    overflow: "hidden",
  },
  moveRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 12,
  },
  moveRowBorder: { borderTopWidth: 1, borderTopColor: C.white4 },
  moveNum: { color: C.white35, fontSize: 12, width: 28 },
  moveWhite: { color: "#fff", fontSize: 13, fontWeight: "600", flex: 1 },
  moveBlack: { color: C.white40, fontSize: 13, flex: 1 },

  broadcastNote: {
    backgroundColor: C.dark3,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.white6,
    paddingHorizontal: 16,
    paddingVertical: 18,
    alignItems: "center",
  },
  broadcastNoteText: { color: C.white40, fontSize: 13 },

  winSection: { marginTop: 20 },
  winBar: {
    flexDirection: "row",
    height: 6,
    borderRadius: 3,
    overflow: "hidden",
  },
  winWhite: { backgroundColor: "#e8e8e8" },
  winBlack: { backgroundColor: "#2a2a3a" },
  winLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 5,
  },
  winLabelWhite: { color: "#e8e8e8", fontSize: 11, fontWeight: "700" },
  winLabelCenter: { color: C.white35, fontSize: 10 },
  winLabelBlack: { color: C.white40, fontSize: 11, fontWeight: "700" },
  clockText: { color: C.gold, fontSize: 13, fontWeight: "700", marginTop: 4 },

  paginationRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    marginTop: 12,
  },
  pageBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: C.dark3,
    borderWidth: 1,
    borderColor: C.white8,
    alignItems: "center",
    justifyContent: "center",
  },
  pageBtnDisabled: { opacity: 0.3 },
  pageBtnText: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "600",
    lineHeight: 22,
  },
  pageBtnTextDisabled: { color: C.white35 },
  pageIndicator: {
    color: C.white40,
    fontSize: 13,
    minWidth: 48,
    textAlign: "center",
  },
});
