import { C } from "@/constants/Colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  gradient: { flex: 1 },
  kav: { flex: 1 },
  floatingPiece: {
    position: "absolute",
    fontSize: 28,
    color: C.gold,
    opacity: 0.15,
  },
  inner: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
    paddingVertical: 60,
    paddingBottom: 120,
  },
  logoBox: {
    width: 88,
    height: 88,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: C.gold55,
    backgroundColor: C.gold18,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    shadowColor: C.gold,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 10,
  },
  logoIcon: { fontSize: 46, color: C.gold },
  title: {
    color: C.gold,
    fontSize: 34,
    fontWeight: "900",
    letterSpacing: 6,
  },
  titleSub: {
    color: C.gold2,
    fontSize: 16,
    fontWeight: "400",
    letterSpacing: 12,
    fontStyle: "italic",
    marginTop: 2,
  },
  divider: {
    width: 50,
    height: 1,
    backgroundColor: C.gold,
    opacity: 0.5,
    marginVertical: 12,
  },
  subtitle: {
    color: C.white40,
    fontSize: 13,
    letterSpacing: 1,
    marginBottom: 36,
  },
  form: { width: "100%", gap: 4 },
  inputWrapper: { marginBottom: 14 },
  inputLabel: {
    color: C.gold,
    fontSize: 10,
    letterSpacing: 2,
    fontWeight: "700",
    marginBottom: 6,
  },
  input: {
    backgroundColor: C.dark3,
    color: "#fff",
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingVertical: 15,
    fontSize: 15,
    borderWidth: 1,
    borderColor: C.gold33,
  },
  btnWrapper: { marginTop: 10 },
  btn: {
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
    shadowColor: C.gold,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 8,
  },
  btnDisabled: { opacity: 0.6 },
  btnText: {
    color: C.dark,
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: 2,
  },
  linkBtn: { marginTop: 28, alignItems: "center" },
  linkText: { color: C.white40, fontSize: 14 },
  linkBold: { color: C.gold, fontWeight: "600" },
});
