import { C } from "@/constants/Colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.dark },
  center: {
    flex: 1,
    backgroundColor: C.dark,
    alignItems: "center",
    justifyContent: "center",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 12,
    backgroundColor: C.dark,
    gap: 12,
  },
  backBtn: { paddingVertical: 4 },
  backText: { color: C.gold, fontSize: 15 },
  headerInfo: { flex: 1 },
  leagueName: { fontSize: 18, color: "#fff", fontWeight: "700" },
  headerMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 2,
  },
  metaText: { fontSize: 12, color: C.white40 },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  shareBtn: {
    backgroundColor: C.dark3,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: C.gold55,
  },
  shareBtnText: { color: C.gold, fontSize: 13, fontWeight: "600" },
  inviteBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.gold18,
    marginHorizontal: 16,
    marginBottom: 4,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: C.gold33,
  },
  inviteLabel: { color: C.white40, fontSize: 12, marginRight: 8 },
  inviteCode: {
    color: C.gold,
    fontSize: 16,
    fontWeight: "700",
    fontFamily: "monospace",
    flex: 1,
  },
  inviteShare: { color: C.gold, fontSize: 13 },
  tabs: {
    flexDirection: "row",
    marginHorizontal: 16,
    marginBottom: 8,
    backgroundColor: C.dark3,
    borderRadius: 12,
    padding: 4,
  },
  tab: { flex: 1, paddingVertical: 8, alignItems: "center", borderRadius: 10 },
  tabActive: { backgroundColor: C.dark2 },
  tabText: { color: C.white40, fontSize: 13, fontWeight: "600" },
  tabTextActive: { color: C.gold },
  content: { padding: 16, paddingBottom: 40 },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 17,
    color: "#fff",
    fontWeight: "600",
    marginBottom: 12,
  },
  addBtn: {
    backgroundColor: C.accent,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  addBtnText: { color: "#fff", fontSize: 13, fontWeight: "600" },
  empty: { alignItems: "center", paddingTop: 40 },
  emptyIcon: { fontSize: 40, marginBottom: 12 },
  emptyText: { color: C.white40, fontSize: 15, marginBottom: 20 },
  pickBtn: {
    backgroundColor: C.accent,
    borderRadius: 12,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  pickBtnText: { color: "#fff", fontWeight: "600" },
  playerCard: {
    backgroundColor: C.dark3,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: C.white8,
    flexDirection: "row",
    alignItems: "center",
  },
  tierBadge: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  tierText: { fontSize: 13, fontWeight: "700" },
  playerInfo: { flex: 1 },
  playerName: {
    fontSize: 15,
    color: "#fff",
    fontWeight: "600",
    marginBottom: 2,
  },
  playerSub: { fontSize: 12, color: C.white40 },
  playerRating: { fontSize: 16, color: C.gold, fontWeight: "700" },
  standingRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.dark3,
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: C.white8,
  },
  rank: { fontSize: 16, color: C.white40, fontWeight: "700", width: 36 },
  standingInfo: { flex: 1 },
  standingTeam: { fontSize: 15, color: "#fff", fontWeight: "600" },
  standingUser: { fontSize: 12, color: C.white40 },
  standingPoints: { fontSize: 18, color: C.gold, fontWeight: "700" },
  ptsLabel: { fontSize: 11, color: C.white40 },
  infoCard: {
    backgroundColor: C.dark3,
    borderRadius: 14,
    padding: 4,
    borderWidth: 1,
    borderColor: C.white8,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.white6,
  },
  infoLabel: { color: C.white40, fontSize: 14 },
  infoValue: { color: "#fff", fontSize: 14, fontWeight: "500" },
  leaveBtn: {
    marginTop: 24,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: C.red,
  },
  leaveBtnText: { color: C.red, fontWeight: "600", fontSize: 16 },
});
