import { C } from "@/constants/Colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.dark },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 60,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 12,
  },
  backBtn: { paddingVertical: 4 },
  backText: { color: C.gold, fontSize: 15 },
  title: { fontSize: 20, color: "#fff", fontWeight: "700" },
  filters: { paddingHorizontal: 16, paddingBottom: 8 },
  search: {
    backgroundColor: C.dark3,
    color: "#fff",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    borderWidth: 1,
    borderColor: C.white8,
    marginBottom: 12,
  },
  tiers: { flexDirection: "row", gap: 8 },
  tierBtn: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: C.dark3,
    borderWidth: 1,
    borderColor: C.white8,
  },
  tierBtnActive: { borderColor: C.gold55, backgroundColor: C.gold18 },
  tierBtnText: { color: C.white40, fontSize: 13, fontWeight: "600" },
  list: { padding: 16, paddingTop: 8 },
  emptyText: { color: C.white40, fontSize: 15, textAlign: "center" },
  card: {
    backgroundColor: C.dark3,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: C.white8,
    flexDirection: "row",
    alignItems: "center",
  },
  tierBadge: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  tierText: { fontSize: 13, fontWeight: "700" },
  playerInfo: { flex: 1 },
  playerName: {
    fontSize: 15,
    color: "#fff",
    fontWeight: "600",
    marginBottom: 2,
  },
  playerSub: { fontSize: 12, color: C.white40 },
  addBtn: {
    backgroundColor: C.accent,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  addBtnDisabled: { opacity: 0.4 },
  addBtnText: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "300",
    lineHeight: 28,
  },
});
